language: python
python: 3.6
cache:
    pip: true
services:
    - mysql
before_install:
    - mysql -e "CREATE USER 'TaDa'@'localhost' identified by '1234';"
    - mysql -e "GRANT ALL PRIVILEGES ON *.* to 'TaDa'@'localhost';"
    - mysql -e 'CREATE DATABASE TaDa_DB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'
    - cd TaDa/backend
install:
    - pip install django
    - pip install coverage
    - pip install python-coveralls
    - pip install mysqlclient
    - pip install django-mysql
script:
    - coverage run --source='./' --omit='*wsgi*,manage.py' manage.py test
after_success:
    - coveralls

