language: python
python: 3.6
cache:
    pip: true
install:
    - cd TaDa/backend
    - pip install django
    - pip install coverage
    - pip install python-coveralls
    - sudo apt-get install mysql-community-server
    - sudo apt-get install python-dev python3-dev
    - sudo apt-get install libmysqlclient-dev
    - pip install mysqlclient
    - pip install mysql-python
script:
    - coverage run --source='./user' manage.py test
after_success:
    - coveralls

