language: python
python: 3.6
cache:
    pip: true
services:
    - mysql
before_install:
    - mysql -e 'CREATE DATABASE TaDa_DB;'
    - cd TaDa/backend
install:
    - pip install django
    - pip install coverage
    - pip install python-coveralls
    - pip install mysqlclient
    - pip install django-mysql
script:
    - coverage run --source='./user' manage.py test
after_success:
    - coveralls

